### PR TITLE
Added xml-security-impl dependency to fix build failure issue

### PR DESCRIPTION
**Pull request by civild**
Currently a clean build on Java 1.8.0_60 fails due to a dependency on an internal package (which I assume is no longer present in that version of Java):

```
joe$ mvn -q install
[ERROR] COMPILATION ERROR : 
[ERROR] /Users/Joe/Projects/MutabilityDetector/src/test/java/org/mutabilitydetector/WellKnownJavaTypesTest.java:[45,59] package com.sun.org.apache.xml.internal.security.encryption does not exist
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project MutabilityDetector: Compilation failure
[ERROR] /Users/Joe/Projects/MutabilityDetector/src/test/java/org/mutabilitydetector/WellKnownJavaTypesTest.java:[45,59] package com.sun.org.apache.xml.internal.security.encryption does not exist

```

The xml-security-impl dependency includes this missing package and solves the [problem from build 111](https://travis-ci.org/MutabilityDetector/MutabilityDetector/builds/191987651).

### CODE REVIEW

**Comment by vik4es** [comment]
Hello! It seems that library has usage of missing package only in imports in WellKnownJavaTypesTest class. And this import is unused. In my pull request 'issue_98_fix' I have removed all unused imports for this class and after that build was successful.

**Comment by Grundlefleck** [comment]
As @vik4es says, the dependency may not need to be added since it may not be a required dependency, but I want to refresh my memory of why that was imported. I may want to reinstate whatever test case was taken out due to the compile failure.

If I find the dependency is unused I'll take it out later, but I'll keep it for now.

Many thanks for taking the time to provide a fix!

**Comment by civild** [comment]
Great thanks - this was my first ever pull request, good to get my feet wet. 🙌
